basePath: /
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  k3gin_app_schema.ErrorItem:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  k3gin_app_schema.ErrorResult:
    properties:
      error:
        $ref: '#/definitions/k3gin_app_schema.ErrorItem'
    type: object
info:
  contact:
    email: yelei@3k.com
    name: STones_
  description: RBAC scaffolding based on GIN + GORM + WIRE.
  title: k3gin
  version: 1.0.1
paths:
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: get userinfo by ID,UserName
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/k3gin_app_schema.ErrorResult'
      summary: Show user
      tags:
      - QueryAPI
schemes:
- http
- https
swagger: "2.0"
