// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"k3gin/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	routerRouter := &router.Router{}
	engine := router.InitGinEngine(routerRouter)
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	injector := &Injector{
		Engine: engine,
		DB:     db,
	}
	return injector, func() {
		cleanup()
	}, nil
}
