// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cron

import (
	"k3gin/app/cache/redisx"
	"k3gin/app/gormx"
	"k3gin/app/httpx"
)

// Injectors from wire.go:

func BuildCronInject() (*Cron, func(), error) {
	db, cleanup, err := gormx.InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	store, cleanup2, err := redisx.InitRedisStore()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := httpx.InitHttp()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cron := &Cron{
		Db:         db,
		Redis:      store,
		HttpClient: client,
	}
	return cron, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
