// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cron

import (
	"k3gin/app/cache/redisx"
	"k3gin/app/gormx"
	"k3gin/app/grpcx"
	"k3gin/app/httpx"
)

// Injectors from wire.go:

func BuildCronInject() (*Cron, func(), error) {
	cron := InitV3Cron()
	client, cleanup, err := httpx.InitHttp()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := gormx.InitGormDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	store, cleanup3, err := redisx.InitRedisStore()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientConn, cleanup4, err := grpcx.InitClientRPC()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cronCron := &Cron{
		V3Cron:     cron,
		HttpClient: client,
		DB:         db,
		Store:      store,
		GrpcClient: clientConn,
	}
	return cronCron, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
